spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 399776640628-7k2voan97phatcpgop2pjhhfqegpb40m.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: bd699a578711354000bda5a0aaead50a # rest api key
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
